#! /usr/bin/env Rscript

currVer = "v1.0.1"

## Colored output settings
UI_frame_color = "yellow"
command_color = "yellow"
file_colors = c("light red", "light magenta")
splash_color = "light green"
splash_delete_color = "red"

## For clean printing, file names are trimmed when too long. File
## names are trimmed to the following value, and have three periods
## (ellipses) added to the name, making the final name
## (max_name_length + 3) characters long
max_name_length = 63

## Parse command line arguments if present
args = commandArgs(TRUE)

if (is.na(args[1])) {
    root = "~/media/Television"
} else {
    root = args[1]
}

ccat <- function(color, ptext, ...) {

  colorCode = switch(tolower(color),
    black = 30,
    red = 31,
    green = 32,
    yellow = 33,
    blue = 34,
    magenta = 35,
    cyan = 36,
    "light gray" = 37,
    "dark gray" = 90,
    "light red" = 91,
    "light green" = 92,
    "light yellow" = 93,
    "light blue" = 94,
    "light magenta" = 95,
    "light cyan" = 96,
    white = 97,
    39) # Default foreground color for current terminal

  ## Set color
  colorFormat = sprintf("\033[%dm", colorCode)

  ftext = paste(colorFormat, ptext, "\033[0m", sep="")
  cat(ftext, ...)
} ## End of function ccat

getFileData <- function(root) {
    ## Recursively search root directory for video files and return a
    ## data frame containing file paths and file names (without path
    ## or file extension info)

    ## Regexp that matches video files
    videoRegex = ".+\\.flv$|mov$|mp4$|wmv$|mkv$|mov$|avi$|mpg$|swf$"

    ## Read in the files from the specified root directory
    filePath = list.files(root, videoRegex,
        recursive=TRUE, full.names=T)

    ## File names (with path or extension)
    fileName = sub("\\.[[:alnum:]]{3}", "", basename(filePath))

    ## By default, files are returned in the order in which the
    ## directory was traversed. This means that the original directory
    ## name rather than the file name determines how it is
    ## sorted. Here, we instead sort alphabetically by file *name*
    ## instead and use this new permutation when creating our data
    ## frame below
    idx = order(fileName)

    ## Create a data frame and return
    return(data.frame(filePath = filePath[idx], fileName =
                      fileName[idx],
                      stringsAsFactors = FALSE))

}

trashFiles <- function(flist) {
    ## Deletes (moves to trash) files contained in flist. In addition,
    ## if trashSimilar == TRUE, files with the same name but different
    ## extensions are deleted as well! This takes care of subtitle
    ## files, etc. that would otherwise accumulate on the
    ## system. However, if you have two copies of the same video in
    ## different formats (e.g., .avi and .mkv), they will both be
    ## deleted by this!

    ## Regular expression that matches video files ending with
    ## supported file extensions
    videoRegex = ".+\\.flv$|mov$|mp4$|wmv$|mkv$|mov$|avi$|mpg$|swf$"

    ## Location of trash directory on the current system
    ## TODO: make this not hardwired
    trashPath = "~/.local/share/Trash/files"
    
    for (currFile in flist) {

        ## Directory for current file
        fileDir = dirname(currFile)
        ## File name of current file
        fileName = sub("\\.[[:alnum:]]{3}", "", basename(currFile))
        
        ## This is annoying, but if the file has () in it, they must
        ## be escaped to avoid the grouping behavior of parentheses in
        ## regexps
        quotedFileName = gsub("\\(", "\\\\(", fileName)
        ## Same goes for .
        quotedFileName = gsub("\\.", "\\\\.", quotedFileName)

        ## We construct a regular expression that matches files with
        ## the same file name but different extensions
        fileRegex = paste("^", quotedFileName, "\\.[[:alnum:]]{3}$", sep="")

        ## File all files in the current directory with the same name
        ## (but different extension)
        myFiles = list.files(fileDir, fileRegex, full.names=TRUE) 

        ## Don't include the current file for deletion, which would be
        ## found by the above regexp
        myFiles = setdiff(myFiles, file.path(fileDir,
            basename(currFile))) 

        ## Don't delete video files with the same name (if the user
        ## has multiple copies of the same video in different formats,
        ## we don't want to delete those copies)
        idx = grep(videoRegex, myFiles)
        
        ## This removes videos files from our vector (so that they do
        ## NOT get deleted)
        if (length(idx) > 0) {myFiles = myFiles[-idx]}

        ## Add the original file to the deletion list
        myFiles = c(myFiles, currFile)

        ## We're finally ready for deleting files associated with
        ## currFile as well as currFile itself. Now we delete them
        ## (actually, we move them to the trash)
        file.rename(myFiles, file.path(trashPath, basename(myFiles)))
    }
}

splashLogo <- function(color="green") {
ccat(color = color, c(
       "\t\t\t\t\t    __                  \n", 
       "\t\t\t\t\t   / /_  ____  ____ ___ \n", 
       "\t\t\t\t\t  / __ \\/ __ \\/ __ `__ \\\n", 
       "\t\t\t\t\t / /_/ / /_/ / / / / / /\n", 
       "\t\t\t\t\t/_.___/ .___/_/ /_/ /_/ \n", 
       sprintf("\t\t\t\t\t     /_/           %s\n", currVer)),
     sep = "")
}

videoDuration <- function(filePath) {
    ## Calls mplayer to determine the duration of the video file at
    ## filePath and returns the duration in seconds

    ## Grab the video's meta-data using mplayer
    tmp = system(
        paste("mplayer -vo null -ao null -identify -frames 0",
              shQuote(filePath[1]), sep=" "),
        intern = T, ignore.stderr = T)

    ## Find the duration of the video in the meta-data
    x = grep("ID_LENGTH.*", tmp, value=T)
    ## Extract the number of seconds
    m = regexpr("[[:digit:]]+\\.*[[:digit:]]*$", x)
    tmp = regmatches(x, m)
    ## Convert to minutes and return
    return(round(as.numeric(tmp) / 60, 1))
}

displayFiles <- function(flist, numVideos) {
    ## Displays a list of files in pretty fashion
    
    system("clear")
    splashLogo(splash_color)
    ccat(color = UI_frame_color,
        c(#"-------------------------------------",
          #"-----------------------------\n",
          "\n",
          sprintf("%s\t%s\t\t\t\t\t\t(%d Files)\n", "Item",
                "Title", numVideos), 
          "-------------------------------------",
          "-----------------------------\n"), sep="")

    for (i in 1:length(flist$fileName)) {
      ## Trim file name if it is too long to display nicely in tabular
      ## form
      fname = flist$fileName[i]
      if (nchar(fname) > max_name_length) {
        fname = paste(strtrim(fname, max_name_length),
          "...", sep="") 
      }
      
      ## Alternate color presentation
      ccat(color = file_colors[i %% 2 + 1],
           sprintf("%d\t%s\n", i, fname))
      }
}

handleResp <- function(d, resp, startIdx, maxFiles, maxItem) {
    ## Manages user input and calls the appropriate function

    ## Try to handle the user's unpredictable input
    tryCatch(
        {
            ## Initial letter/number of resp determines behavior
            initialResp = substr(resp, 1, 1)

            ## If the resp is just a number, play the corresponding video
            if (length(grep("[[:digit:]]", initialResp)) == 1) {
                ## Play corresponding video and wait for it to return
                respAsNum = as.numeric(resp)
                vidChoice = respAsNum + (startIdx - 1)

                ## Only allow reasonable item numbers
                if (respAsNum <1 | respAsNum > maxItem) {
                    ## Do nothing... the user has asked for an illegal
                    ## item number
                    return(startIdx)
                } 

                cat(sprintf("Playing %s...", d$fileName[vidChoice]))
                system(paste("mplayer -really-quiet",
                             shQuote(d$filePath[vidChoice]),
                             sep=" "),
                       wait=T, ignore.stdout = TRUE,
                       ignore.stderr = TRUE) 

                ## Return the original startIdx (which means the browser will
                ## simply return to its previous state after the video has
                ## finished playing)
                return(startIdx)
            }

            ## TODO: use switch instead of if/else
            ## The user could have asked to see the next page of videos
            if (tolower(initialResp) == "n") {
                ## Return index of the next page of results
                return(startIdx + maxFiles)
            } else if (tolower(initialResp) == "p") {
                ## The user has asked to see the previous page of videos
                return(startIdx - maxFiles)
            } else if (tolower(initialResp) == "q") {
                ## The user wants to quit
                return(0)

            } else if (tolower(initialResp) == "t") {
                ## Return to the top page of results
                return(1)
            } else if (tolower(initialResp) == "d") {
                ## Switch to deletion mode
                tmp = deleteMode(d, resp, startIdx, maxFiles, maxItem)
                if (tmp == 1) {
                    ## Something was deleted... refresh the file list
                    return(-1)
                } else {
                    return(startIdx)
                }
            } else if (tolower(initialResp) == "r") {
                ## The user wants the file list to refresh due to
                ## changes on disk
                return(-1)
            } else {
                ## The response is illegal. If it didn't cause an
                ## error, we just return the current state of things
                return(startIdx)
            }
            
        },
        error = function(e) {
            cat('Unknown Command!\n')
        })
    return(startIdx)
}

deleteMode <- function(d, resp, startIdx, maxFiles, maxItem) {
    ## Resp contains the user's input. If you've made it here, the
    ## first character in response is "d", followed by 1 or more
    ## numbers separated by spaces

    ## Drop the "d", and keep the remaining number(s) as indexes
    idx = as.numeric(unlist(strsplit(resp, " "))[-1])

    ## Error checking. Don't allow user to delete files not present on
    ## the current page of results
    if (min(idx) <1 | max(idx) > maxItem) {
        ## Do nothing... the user has asked for an illegal
        ## item number
        return(0)
    } 

    ## Account for current page of results so that the proper data
    ## file is trashed
    idx = idx + (startIdx - 1)

    ## Isolate the corresponding files and cue them for deletion
    deletionPaths = d$filePath[idx]
    deletionNames = d$fileName[idx]
    N_items = length(deletionNames)
    
    ## Clear the screen
    system("clear")

    splashLogo(splash_delete_color)
    
    ccat(color = UI_frame_color,
         c(#"----------------------------------",
           #"--------------------------------\n",
           "\n",
           "Files to trash\n",
           "----------------------------------",
           "--------------------------------\n"), sep="")
    
    for (i in 1:N_items) {
      ccat(color = "light red", sprintf("%s...\n", deletionNames[i]))
    }
    ## Pad the screen so the user experience isn't affected by a
    ## suddenly small screen
    cat(paste(rep("\n", (maxFiles - N_items - 1)), collapse=""))
    
    ccat(color= UI_frame_color,
         c("\nAccessory files (subtitle files, etc.) will also be trashed\n",
           "\nTrash files? [Y]es or [n]o\n>>", sep=""))
    resp = readLines(file("stdin"), 1)

    if (resp == "Y") {
        trashFiles(deletionPaths)
        cat("Trashed... Press Enter to continue")
        readLines(file("stdin"), 1)
        return(1)
    } else {
        cat("Aborted... Press Enter to continue")
        readLines(file("stdin"), 1)
        return(0)
    }
}

fileBrowser <- function(root) {
    ## Controls how many files are displayed at a time, and acts as a
    ## dispatcher for different functionality, including the playback
    ## and deletion of videos.

    ## Find videos files recursively within root directory
    d = getFileData(root)

    browsep = TRUE
    ## The starting video index in the browser window. This is used to
    ## display a subset of a very long list of videos
    startIdx = 1
    ## How many files to display onscreen at once
    maxFiles = 15
    numVideos = dim(d)[1]

    ## Given the number of files per page, what is the total pages of
    ## results possible?
    maxPage = ceiling(numVideos / maxFiles)
    
    while (browsep) {
        ## Double check that our indexes are not out of range
        if (startIdx < 1) {startIdx = 1}
        endIdx = startIdx + (maxFiles - 1)
        if (endIdx > numVideos) {endIdx = numVideos}

        ## Determine current page number
        if (startIdx == 1) {
            currPage = 1
        } else {
            currPage = (startIdx + (maxFiles - 1)) / maxFiles
        }
        
        ## Display the current page of results
        displayFiles(d[startIdx:endIdx,], numVideos)
        ## For the current page, maxItem is the maximum allowable item
        ## number response
        maxItem = dim(d[startIdx:endIdx,])[1]
        ## If the final page of results has less entries than
        ## maxFiles, then we pad with extra blank lines so that the
        ## user doesn't experience the input prompt moving around
        cat(paste(rep("\n", (maxFiles - maxItem)), collapse=""))

        ## Get user input with custom prompt
        ccat(color = command_color,
             sprintf("\nItem # to play\t\t\t\t\t\t Page %d/%d\n", 
                     currPage, maxPage))
        if (endIdx < numVideos & startIdx > 1) {
          ccat(color = command_color, "[n]ext or [p]revious page\n")
        } else if (endIdx < numVideos) {
          ccat(color = command_color, "[n]ext page\n")
        } else if (startIdx > 1) {
          ccat(color = command_color, "[p]revious page\n")
        } 
        ccat(color = command_color, ">> ")
        
        resp = readLines(file("stdin"), 1)
        newStartIdx = handleResp(d, resp, startIdx, maxFiles, maxItem) 

        ## If handleResp returned zero, the user has asked to quit.
        if (newStartIdx == 0) {
            browsep = FALSE
        }

        ## Reset the index for the current page of results
        if (newStartIdx < numVideos) {
            startIdx = newStartIdx
        }

        ## If the index is -1, a refresh has been requested (either by
        ## the user or by another function such as deleteMode)
        if (newStartIdx == -1) {
            d = getFileData(root)
            numVideos = dim(d)[1]
            startIdx = 1
        } 
            
    }
    ## We're done

} 

## Auto-run below here

## Start the file browser
fileBrowser(root)
## We're done... clear the terminal and exit
system("clear")

## End of file m
